### ISSUE TITLE
Connected animation support?

### ISSUE THREAD

**Issue by TareqAteik** [nventive/Uno#167]
This might be tricky to implement, but just wondering if its on roadmap?
Any plans for it?
https://docs.microsoft.com/en-us/windows/uwp/design/motion/connected-animation

![alt text](https://i.stack.imgur.com/XW6Vr.gif "animation")

**Comment by jeromelaban** [comment]
Thanks for your interest in Uno!

Yes, connected animations are on our radar, we'll add that to our roadmap.

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** This is a feature request asking whether connected animation support is on the roadmap. The body contains no specific broken behavior, no code sample, and no reproduction steps — it is purely a feature enquiry. Connected animations are a complex WinUI animation API and this issue serves as a tracking request rather than a bug report.

**Comment by lextm** [comment]
This remains missing, so when porting Wino Mail to Uno I hit two related. I list them below for future reference.

## `Microsoft.UI.Composition.Compositor.CreateImplicitAnimationCollection()` — `NotImplementedException`

```
System.NotImplementedException: The member ImplicitAnimationCollection
Compositor.CreateImplicitAnimationCollection() is not implemented.
   at Microsoft.UI.Composition.Compositor.CreateImplicitAnimationCollection()
       in C:\a\1\s\src\Uno.UI.Composition\Generated\3.0.0.0\Microsoft.UI.Composition\Compositor.cs:line 265
```

Throwing from a constructor (Wino's
`MailItemDisplayInformationControl` uses it for hover effects) aborts the
entire `DataTemplate` materialization for the item. The visible failure mode
is that the whole `ListView` shows **zero items** even though the
`ItemsSource` is populated — extremely confusing to debug.

The known workaround is to guard every `EnableImplicitAnimation` /
`Compositor.CreateImplicitAnimationCollection` call site with
`#if WINDOWS_APP_SDK`. Lose the per-item hover/offset animations on desktop.

## `ConnectedAnimationService.GetForCurrentView()` — `NotImplementedException`

```
System.NotImplementedException: The member ConnectedAnimationService
ConnectedAnimationService.GetForCurrentView() is not implemented.
   at Microsoft.UI.Xaml.Media.Animation.ConnectedAnimationService.GetForCurrentView()
       in C:\a\1\s\src\Uno.UI\Generated\3.0.0.0\Microsoft.UI.Xaml.Media.Animation\ConnectedAnimationService.cs:line 66
```

Throws from `Page.OnNavigatedTo` if the page uses connected
animations to drive a hero-element transition. In Wino's
`MailRenderingPage`, the whole page never finishes navigation, leaving the
mail body permanently blank.
